<a href="https://colab.research.google.com/github/AARYA2k04/Predicting-Efficacy-of-ALS-Drugs-using-RNN-and-LSTM/blob/main/features.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import files
uploaded=files.upload()

Saving ec50.csv to ec50.csv


In [ ]:
pip install rdkit


     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 34.4/34.4 MB 16.4 MB/s eta 0:00:00


In [ ]:
import pandas as pd
from rdkit import Chem
import networkx as nx

# Load the dataset
df = pd.read_csv("ec50.csv")

# Function to convert SMILES to graph
def smiles_to_graph(smiles):
    # Load molecule from SMILES
    molecule = Chem.MolFromSmiles(smiles)
    if molecule is None:
        return None
    # Create an empty graph
    graph = nx.Graph()
    # Add nodes for atoms
    for atom in molecule.GetAtoms():
        graph.add_node(atom.GetIdx(), atomic_number=atom.GetAtomicNum())
    # Add edges for bonds
    for bond in molecule.GetBonds():
        graph.add_edge(bond.GetBeginAtomIdx(), bond.GetEndAtomIdx(), bond_type=bond.GetBondType())
    return graph

# Convert SMILES to graphs
graphs = []
for smiles in df['canonical_smiles']:
    graph = smiles_to_graph(smiles)
    if graph is not None:
        graphs.append(graph)
print(graphs)

# Now 'graphs' is a list of NetworkX graphs representing molecules from your dataset


[<networkx.classes.graph.Graph object at 0x789170936ef0>, <networkx.classes.graph.Graph object at 0x7891709372b0>, <networkx.classes.graph.Graph object at 0x789170937310>, <networkx.classes.graph.Graph object at 0x789170936170>, <networkx.classes.graph.Graph object at 0x789170936200>, <networkx.classes.graph.Graph object at 0x7891351af130>, <networkx.classes.graph.Graph object at 0x7891351aee90>, <networkx.classes.graph.Graph object at 0x7891351af370>, <networkx.classes.graph.Graph object at 0x7891351af550>, <networkx.classes.graph.Graph object at 0x7891351aefe0>, <networkx.classes.graph.Graph object at 0x7891351af0d0>, <networkx.classes.graph.Graph object at 0x7891351af400>, <networkx.classes.graph.Graph object at 0x7891351af790>, <networkx.classes.graph.Graph object at 0x7891351af880>, <networkx.classes.graph.Graph object at 0x7891351afee0>, <networkx.classes.graph.Graph object at 0x7891351aeec0>, <networkx.classes.graph.Graph object at 0x7891351af9d0>, <networkx.classes.graph.Graph 

In [ ]:
import pandas as pd
from rdkit import Chem
import networkx as nx

# Load the dataset
df = pd.read_csv("ec50.csv")

# Function to convert SMILES to graph and extract features
def smiles_to_graph_and_features(smiles):
    # Load molecule from SMILES
    molecule = Chem.MolFromSmiles(smiles)
    if molecule is None:
        return None, None, None

    # Create an empty graph
    graph = nx.Graph()

    # Initialize dictionaries to store node and edge features
    node_features = {}
    edge_features = {}

    # Add nodes for atoms
    for atom in molecule.GetAtoms():
        atom_idx = atom.GetIdx()
        graph.add_node(atom_idx)
        # Add node features
        node_features[atom_idx] = {
            'atomic_number': atom.GetAtomicNum(),
            'formal_charge': atom.GetFormalCharge(),
            'hybridization': atom.GetHybridization(),
            'num_hydrogens': atom.GetTotalNumHs(),

            # Add more features as needed
        }

    # Add edges for bonds
    for bond in molecule.GetBonds():
        begin_atom_idx = bond.GetBeginAtomIdx()
        end_atom_idx = bond.GetEndAtomIdx()
        # Add edge features
        edge_features[(begin_atom_idx, end_atom_idx)] = {
            'bond_type': bond.GetBondType(),
            # Add more features as needed
        }
        graph.add_edge(begin_atom_idx, end_atom_idx)

    return graph, node_features, edge_features

# Convert SMILES to graphs and extract features
graphs = []
node_features_list = []
edge_features_list = []
for smiles in df['canonical_smiles']:
    graph, node_features, edge_features = smiles_to_graph_and_features(smiles)
    if graph is not None:
        graphs.append(graph)
        node_features_list.append(node_features)
        edge_features_list.append(edge_features)
print(node_features_list)
print(edge_features_list)
# Now 'graphs' is a list of NetworkX graphs representing molecules
# 'node_features_list' contains node features for each molecule
# 'edge_features_list' contains edge features for each molecule


[{0: {'atomic_number': 8, 'formal_charge': 0, 'hybridization': rdkit.Chem.rdchem.HybridizationType.SP2, 'num_hydrogens': 0}, 1: {'atomic_number': 6, 'formal_charge': 0, 'hybridization': rdkit.Chem.rdchem.HybridizationType.SP2, 'num_hydrogens': 0}, 2: {'atomic_number': 6, 'formal_charge': 0, 'hybridization': rdkit.Chem.rdchem.HybridizationType.SP2, 'num_hydrogens': 1}, 3: {'atomic_number': 6, 'formal_charge': 0, 'hybridization': rdkit.Chem.rdchem.HybridizationType.SP2, 'num_hydrogens': 0}, 4: {'atomic_number': 6, 'formal_charge': 0, 'hybridization': rdkit.Chem.rdchem.HybridizationType.SP3, 'num_hydrogens': 2}, 5: {'atomic_number': 8, 'formal_charge': 0, 'hybridization': rdkit.Chem.rdchem.HybridizationType.SP2, 'num_hydrogens': 0}, 6: {'atomic_number': 6, 'formal_charge': 0, 'hybridization': rdkit.Chem.rdchem.HybridizationType.SP2, 'num_hydrogens': 0}, 7: {'atomic_number': 6, 'formal_charge': 0, 'hybridization': rdkit.Chem.rdchem.HybridizationType.SP2, 'num_hydrogens': 1}, 8: {'atomic_nu

In [ ]:
# Convert 'node_features_list' to a DataFrame
node_features_df = pd.DataFrame(node_features_list)

# Save the DataFrame to a CSV file
node_features_df.to_csv("node_features.csv", index=False)

# Convert 'node_features_list' to a DataFrame
edge_features_df = pd.DataFrame(edge_features_list)

# Save the DataFrame to a CSV file
edge_features_df.to_csv("edge_features.csv", index=False)

In [ ]:
import rdkit
from rdkit import Chem
import networkx as nx

In [ ]:
import torch
import torch.nn as nn
import torch.nn.functional as F


In [ ]:
import pandas as pd

# Load node features from CSV
node_features_df = pd.read_csv("node_features.csv", sep="\t", header=None)


In [ ]:
import ast
import torch

# Convert each cell (dictionary) in the DataFrame to a tensor
node_tensors = []
for row in node_features_df.values:
    features_list = []
    for cell in row:
        node_features = ast.literal_eval(cell)  # Convert string dictionary to actual dictionary
        features_list.append(list(node_features.values()))  # Extract values from the dictionary
    features_tensor = torch.tensor(features_list, dtype=torch.float32)
    node_tensors.append(features_tensor)

# Stack tensors to create the final node input tensor
node_input_tensor = torch.stack(node_tensors)


AttributeError: 'tuple' object has no attribute 'values'

In [ ]:
import pandas as pd

# Load node_features.csv into a DataFrame
node_features_df = pd.read_csv("node_features.csv")

# Now, you can use the provided code snippet to process the node features


In [ ]:
import pandas as pd
import ast
import torch
from torch_geometric.data import Data

# Load node_features.csv into a DataFrame
node_features_df = pd.read_csv("node_features.csv")

# Define lists to store node and edge tensors
node_tensors = []
edge_tensors = []

# Process node features
for row in node_features_df.values:
    features_list = []
    for cell in row:
        node_features = ast.literal_eval(cell)  # Convert string dictionary to actual dictionary
        features_list.append(list(node_features.values()))  # Extract values from the dictionary
    features_tensor = torch.tensor(features_list, dtype=torch.float32)
    node_tensors.append(features_tensor)

data = Data(x=node_tensors, edge_index=edge_tensors)

# Now you can use the 'data' object in your graph convolutional neural network (GCNN) architecture


In [ ]:
pip install torch_geometric

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 5.4 MB/s eta 0:00:00


In [ ]:
import pandas as pd
import tensorflow as tf
import ast
from rdkit import Chem
from rdkit.Chem import AllChem
from tensorflow.keras.layers import Input, Dense
from tensorflow.keras.models import Model
from tensorflow.keras.utils import to_categorical

# Load the dataset
df = pd.read_csv('ec50.csv')

# Define the maximum number of heavy atoms in a molecule
max_atoms = 100

# Define the maximum number of bits in a fingerprint
max_fingerprint_bits = 1024

# Generate the fingerprints for each molecule in the dataset
df['fingerprints'] = df['canonical_smiles'].apply(lambda x: AllChem.GetMorganFingerprintAsBitVect(Chem.MolFromSmiles(x), radius=2, nBits=max_fingerprint_bits))

# Define the input layer for the GCNN model
input_layer = Input(shape=(max_fingerprint_bits,))

dense_layer_1 = Dense(units=128, activation='relu')(input_layer)

# Define the output layer with 1 neuron and sigmoid activation
output_layer = Dense(units=1, activation='sigmoid')(dense_layer_1)

# Define the GCNN model
model = Model(inputs=input_layer, outputs=output_layer)

model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])


In [ ]:
import pandas as pd
from rdkit import Chem
import networkx as nx
import numpy as np

# Load the dataset
df = pd.read_csv("ec50.csv")

# Function to convert SMILES to graph
def smiles_to_graph(smiles):
    # Load molecule from SMILES
    molecule = Chem.MolFromSmiles(smiles)
    if molecule is None:
        return None
    # Create an empty graph
    graph = nx.Graph()
    # Add nodes for atoms
    for atom in molecule.GetAtoms():
        graph.add_node(atom.GetIdx(), atomic_number=atom.GetAtomicNum(), hybridization=atom.GetHybridization(), chiral=atom.GetChiralTag(), formal_charge=atom.GetFormalCharge())
    # Add edges for bonds
    for bond in molecule.GetBonds():
        graph.add_edge(bond.GetBeginAtomIdx(), bond.GetEndAtomIdx(), bond_type=bond.GetBondType())
    return graph

# Define a function to create node

In [ ]:
def create_node_features(graph):
    node_features = []
    for node in graph.nodes(data=True):
        node_feature = [node[1]['atomic_number'], node[1]['hybridization'], node[1]['chiral'], node[1]['formal_charge']]
        node_features.append(node_feature)
    return np.array(node_features)

In [ ]:
def create_edge_features(graph):
    edge_features = []
    for edge in graph.edges(data=True):
        edge_feature = [edge[2]['bond_type'], edge[2]['bond_type'].as_double(), edge[2]['bond_type'].as_integer()]
        edge_features.append(edge_feature)
    return np.array(edge_features)

In [ ]:
def create_edge_features(graph):
    edge_features = []
    for edge in graph.edges(data=True):
        bond_type = edge[2]['bond_type']
        edge_feature = [bond_type, bond_type.GetBondTypeAsDouble(), bond_type.GetBondTypeAsInt()]
        edge_features.append(edge_feature)
    return np.array(edge_features)


In [ ]:
def create_edge_features(graph):
    edge_features = []
    for edge in graph.edges(data=True):
        bond_type = str(edge[2]['bond_type'])
        edge_feature = [bond_type]
        edge_features.append(edge_feature)
    return np.array(edge_features)


In [ ]:
# Convert SMILES to graphs and create feature vectors
node_feature_vectors = []
edge_feature_vectors = []
for smiles in df['canonical_smiles']:
    graph = smiles_to_graph(smiles)
    if graph is not None:
        node_features = create_node_features(graph)
        edge_features = create_edge_features(graph)
        node_feature_vectors.extend(node_features)
        edge_feature_vectors.extend(edge_features)


In [ ]:
def create_node_features(graph):
    node_features = []
    for node in graph.nodes(data=True):
        atomic_number = node[1]['atomic_number']
        hybridization = node[1]['hybridization']
        chiral = node[1]['chiral']
        formal_charge = node[1]['formal_charge']
        # Create the vector in the specified format
        vector = [0, 0, 0, 0, 0, 0]  # Initialize with zeros
        vector[atomic_number] = 1  # Set the atomic number index to 1
        if hybridization is not None:
            vector[1] = 1  # Set hybridization index to 1 if present
        if chiral is not None:
            vector[2] = 1  # Set chiral index to 1 if present
        vector[3] = formal_charge  # Set formal charge
        node_features.append(vector)
    return node_features


In [ ]:
def create_edge_features(graph):
    edge_features = []
    for edge in graph.edges(data=True):
        bond_type = str(edge[2]['bond_type'])
        edge_feature = [bond_type]
        edge_features.append(edge_feature)
    return np.array(edge_features)


In [ ]:
def create_edge_features(graph):
    edge_features = []
    for edge in graph.edges(data=True):
        bond_type = str(edge[2]['bond_type'])
        edge_feature = [bond_type]
        edge_features.append(edge_feature)
    return edge_features


In [ ]:
def create_node_features(graph):
    node_features = []
    for node in graph.nodes(data=True):
        atomic_number = node[1]['atomic_number']
        hybridization = node[1]['hybridization']
        chiral = node[1]['chiral']
        formal_charge = node[1]['formal_charge']
        # Create the vector
        vector = [atomic_number, hybridization, chiral, formal_charge, None]
        node_features.append(vector)
    return node_features


In [ ]:
node_feature_vectors = []
edge_feature_vectors = []
for smiles in df['canonical_smiles']:
    graph = smiles_to_graph(smiles)
    if graph is not None:
        node_features = create_node_features(graph)
        edge_features = create_edge_features(graph)
        node_feature_vectors.extend(node_features)
        edge_feature_vectors.extend(edge_features)

In [ ]:
node_columns = ['Atomic Number', 'Hybridization', 'Chirality', 'Formal Charge', 'Vector']
node_df = pd.DataFrame(node_feature_vectors, columns=node_columns)



In [ ]:
def create_edge_features(graph):
    edge_features = []
    for edge in graph.edges(data=True):
        bond_type = str(edge[2]['bond_type'])
        bond_order = edge[2]['bond_type'].as_integer()  # Assuming the bond order is needed as an integer
        vector = [bond_type, bond_order]
        edge_features.append(vector)
    return edge_features


In [ ]:
node_df.to_csv('node_features.csv', index=False)

In [ ]:
import pandas as pd
from rdkit import Chem
import networkx as nx
import numpy as np

# Load the dataset
df = pd.read_csv("ec50.csv")

# Function to convert SMILES to graph
def smiles_to_graph(smiles):
    # Load molecule from SMILES
    molecule = Chem.MolFromSmiles(smiles)
    if molecule is None:
        return None
    # Create an empty graph
    graph = nx.Graph()
    # Add nodes for atoms
    for atom in molecule.GetAtoms():
        graph.add_node(atom.GetIdx(), atomic_number=atom.GetAtomicNum(), hybridization=atom.GetHybridization(), chiral=atom.GetChiralTag(), formal_charge=atom.GetFormalCharge())
    # Add edges for bonds
    for bond in molecule.GetBonds():
        graph.add_edge(bond.GetBeginAtomIdx(), bond.GetEndAtomIdx(), bond_type=bond.GetBondType())
    return graph

# Define a function to create node feature vectors
def create_node_features(graph):
    node_features = []
    for node in graph.nodes(data=True):
        node_feature = [node[1]['atomic_number'], node[1]['hybridization'], node[1]['chiral'], node[1]['formal_charge']]
        # Add the vector representation
        vector = [0, 0, 0, 0, 0]  # Placeholder for vector representation, modify as needed
        node_feature.extend(vector)
        node_features.append(node_feature)
    return np.array(node_features)

def create_edge_features(graph):
    edge_features = []
    for edge in graph.edges(data=True):
        bond_type = str(edge[2]['bond_type'])
        bond_order = int(edge[2]['bond_type'].GetBondTypeAsDouble())  # Obtain bond order as an integer
        vector = [bond_type, bond_order]
        edge_features.append(vector)
    return np.array(edge_features)


# Convert SMILES to graphs and create feature vectors
node_feature_vectors = []
edge_feature_vectors = []
for smiles in df['canonical_smiles']:
    graph = smiles_to_graph(smiles)
    if graph is not None:
        node_features = create_node_features(graph)
        edge_features = create_edge_features(graph)
        node_feature_vectors.extend(node_features)
        edge_feature_vectors.extend(edge_features)

# Create DataFrames for node and edge features
node_columns = ['Atomic Number', 'Hybridization', 'Chirality', 'Formal Charge', 'Vector1', 'Vector2', 'Vector3', 'Vector4', 'Vector5']  # Adjust column names as needed
node_df = pd.DataFrame(node_feature_vectors, columns=node_columns)

edge_columns = ['Bond Type', 'Bond Type (Integer)']
edge_df = pd.DataFrame(edge_feature_vectors, columns=edge_columns)

# Save node and edge features to CSV files
node_df.to_csv('node_features.csv', index=False)
edge_df.to_csv('edge_features.csv', index=False)

print("Node Features saved to 'node_features.csv'")
print("Edge Features saved to 'edge_features.csv'")


AttributeError: 'BondType' object has no attribute 'GetBondTypeAsDouble'

In [ ]:
from rdkit import Chem
import networkx as nx

# Define a function to convert SMILES to graph
def smiles_to_graph(smiles):
    # Load molecule from SMILES
    molecule = Chem.MolFromSmiles(smiles)
    if molecule is None:
        return None
    # Create an empty graph
    graph = nx.Graph()
    # Add nodes for atoms
    for atom in molecule.GetAtoms():
        graph.add_node(atom.GetIdx(), atomic_number=atom.GetAtomicNum(), hybridization=atom.GetHybridization(), chiral=atom.GetChiralTag(), formal_charge=atom.GetFormalCharge())
    # Add edges for bonds
    for bond in molecule.GetBonds():
        graph.add_edge(bond.GetBeginAtomIdx(), bond.GetEndAtomIdx(), bond_type=bond.GetBondType())
    return graph

# Convert SMILES to graph
smiles = "O=c1cc(COc2cc(Br)cc(Br)c2)[nH][nH]1"
graph = smiles_to_graph(smiles)

# Check if graph is created
if graph is not None:
    print("Molecular graph created successfully.")
else:
    print("Failed to create molecular graph.")


Molecular graph created successfully.


In [ ]:
print(graph)

Graph with 16 nodes and 17 edges


In [ ]:
import pandas as pd
from rdkit import Chem
import networkx as nx

# Load the dataset
df = pd.read_csv("ec50.csv")

# Function to convert SMILES to graph
def smiles_to_graph(smiles):
    # Load molecule from SMILES
    molecule = Chem.MolFromSmiles(smiles)
    if molecule is None:
        return None
    # Create an empty graph
    graph = nx.Graph()
    # Add nodes for atoms
    for atom in molecule.GetAtoms():
        graph.add_node(atom.GetIdx(), atomic_number=atom.GetAtomicNum(), hybridization=atom.GetHybridization(), chiral=atom.GetChiralTag(), formal_charge=atom.GetFormalCharge())
    # Add edges for bonds
    for bond in molecule.GetBonds():
        graph.add_edge(bond.GetBeginAtomIdx(), bond.GetEndAtomIdx(), bond_type=bond.GetBondType())
    return graph

# Convert SMILES to graphs
molecular_graphs = []
for smiles in df['canonical_smiles']:
    graph = smiles_to_graph(smiles)
    if graph is not None:
        molecular_graphs.append(graph)

# Now, molecular_graphs contains the molecular graphs for each SMILES string in df['canonical_smiles']


In [ ]:
import pandas as pd
from rdkit import Chem
import networkx as nx
import numpy as np

# Load the dataset
df = pd.read_csv("ec50.csv")

# Function to convert SMILES to graph
def smiles_to_graph(smiles):
    # Load molecule from SMILES
    molecule = Chem.MolFromSmiles(smiles)
    if molecule is None:
        return None
    # Create an empty graph
    graph = nx.Graph()
    # Add nodes for atoms
    for atom in molecule.GetAtoms():
        graph.add_node(atom.GetIdx(), atomic_number=atom.GetAtomicNum(), hybridization=atom.GetHybridization(), chiral=atom.GetChiralTag(), formal_charge=atom.GetFormalCharge())
    # Add edges for bonds
    for bond in molecule.GetBonds():
        graph.add_edge(bond.GetBeginAtomIdx(), bond.GetEndAtomIdx(), bond_type=bond.GetBondType())
    return graph


In [ ]:
def create_node_features(graph):
    node_features = []
    for node in graph.nodes(data=True):
        atomic_number = node[1]['atomic_number']
        hybridization = str(node[1]['hybridization'])
        chiral = str(node[1]['chiral'])
        formal_charge = node[1]['formal_charge']
        # Vector representation based on the provided description
        vector = [0, 0, 0, 0, 0]  # Initialize vector with zeros
        if atomic_number == 7:
            vector[0] = 1  # Nitrogen
        elif atomic_number == 6:
            vector[1] = 1  # Carbon
        elif atomic_number == 1:
            vector[4] = 1  # Hydrogen
        node_feature = [atomic_number, hybridization, chiral, formal_charge] + vector
        node_features.append(node_feature)
    return np.array(node_features)


In [ ]:

import pandas as pd
from rdkit import Chem
import networkx as nx
import numpy as np

# Load the dataset
df = pd.read_csv("ec50.csv")

# Function to convert SMILES to graph
def smiles_to_graph(smiles):
    # Load molecule from SMILES
    molecule = Chem.MolFromSmiles(smiles)
    if molecule is None:
        return None
    # Create an empty graph
    graph = nx.Graph()
    # Add nodes for atoms
    for atom in molecule.GetAtoms():
        graph.add_node(atom.GetIdx(), atomic_number=atom.GetAtomicNum(), hybridization=atom.GetHybridization(), chiral=atom.GetChiralTag(), formal_charge=atom.GetFormalCharge())
    # Add edges for bonds
    for bond in molecule.GetBonds():
        graph.add_edge(bond.GetBeginAtomIdx(), bond.GetEndAtomIdx(), bond_type=bond.GetBondType())
    return graph

# Define a function to create node feature vectors
def create_node_features(graph):
    node_features = []
    for node in graph.nodes(data=True):
        atomic_number = node[1]['atomic_number']
        hybridization = str(node[1]['hybridization'])
        chiral = str(node[1]['chiral'])
        formal_charge = node[1]['formal_charge']
        # Vector representation based on the provided description
        vector = [0, 0, 0, 0, 0]  # Initialize vector with zeros
        if atomic_number == 7:
            vector[0] = 1  # Nitrogen
        elif atomic_number == 6:
            vector[1] = 1  # Carbon
        elif atomic_number == 1:
            vector[4] = 1  # Hydrogen
        node_feature = [atomic_number, hybridization, chiral, formal_charge] + vector
        node_features.append(node_feature)
    return np.array(node_features)

# Define a function to create edge feature vectors
def create_edge_features(graph):
    edge_features = []
    for edge in graph.edges(data=True):
        bond_type = str(edge[2]['bond_type'])  # Get bond type as a string
        # Vector representation based on the provided description
        vector = [0, 0, 0]  # Initialize vector with zeros
        if bond_type == 'SINGLE':
            vector[2] = 1
        elif bond_type == 'DOUBLE':
            vector[0] = 1
        elif bond_type == 'TRIPLE':
            vector[1] = 1
        edge_feature = [bond_type] + vector
        edge_features.append(edge_feature)
    return np.array(edge_features)


In [ ]:

# Convert SMILES to graphs and create feature vectors
node_feature_vectors = []
edge_feature_vectors = []
for smiles in df['canonical_smiles']:
    graph = smiles_to_graph(smiles)
    if graph is not None:
        node_features = create_node_features(graph)
        edge_features = create_edge_features(graph)
        node_feature_vectors.extend(node_features)
        edge_feature_vectors.extend(edge_features)


In [ ]:
node_columns = ['Atomic Number', 'Hybridization', 'Chirality', 'Formal Charge', 'N', 'C', 'O', 'S', 'H']
node_df = pd.DataFrame(node_feature_vectors, columns=node_columns)
edge_columns = ['Bond Type', 'Single', 'Double', 'Triple']

edge_df = pd.DataFrame(edge_feature_vectors, columns=edge_columns)

# Save node and edge features to CSV files
node_df.to_csv('node_features.csv', index=False)
edge_df.to_csv('edge_features.csv', index=False)

print("Node Features saved to 'node_features.csv'")
print("Edge Features saved to 'edge_features.csv'")


Node Features saved to 'node_features.csv'
Edge Features saved to 'edge_features.csv'


In [ ]:
import numpy as np

# Step 1: Determine the maximum atom number size across all molecules
max_atom_number = max(node_df['Atomic Number'])

# Step 2: Create adjacency matrices for each molecule
adjacency_matrices = []
for smiles in df['canonical_smiles']:
    graph = smiles_to_graph(smiles)
    if graph is not None:
        adjacency_matrix = np.zeros((max_atom_number, max_atom_number))
        for edge in graph.edges():
            atom1 = edge[0]
            atom2 = edge[1]
            adjacency_matrix[atom1][atom2] = 1
            adjacency_matrix[atom2][atom1] = 1  # Assuming undirected graph
        adjacency_matrices.append(adjacency_matrix)

# Step 3: Pad each adjacency matrix with zeros to match the maximum atom number size
padded_adjacency_matrices = []
for adjacency_matrix in adjacency_matrices:
    padded_adjacency_matrix = np.pad(adjacency_matrix, ((0, max_atom_number - adjacency_matrix.shape[0]), (0, max_atom_number - adjacency_matrix.shape[1])), mode='constant')
    padded_adjacency_matrices.append(padded_adjacency_matrix)

# Step 4: Combine padded adjacency matrices into a single adjacency matrix
combined_adjacency_matrix = np.stack(padded_adjacency_matrices, axis=0)


TypeError: 'numpy.str_' object cannot be interpreted as an integer

In [ ]:
import numpy as np

# Define the SMILES string
smiles = "O=c1cc(COc2cc(-c3ccccc3)cc(-c3ccccc3)c2)[nH][nH]1"

# Convert SMILES to graph
graph = smiles_to_graph(smiles)

# Determine the maximum atom number size across all molecules
# Determine the maximum atom number size across all molecules
max_atom_number = int(max(node_df['Atomic Number']))


# Create adjacency matrix
adjacency_matrix = np.zeros((max_atom_number, max_atom_number))

# Fill adjacency matrix based on graph edges
if graph is not None:
    for edge in graph.edges():
        atom1 = edge[0]
        atom2 = edge[1]
        adjacency_matrix[atom1][atom2] = 1
        adjacency_matrix[atom2][atom1] = 1  # Assuming undirected graph

print(adjacency_matrix)


IndexError: index 25 is out of bounds for axis 0 with size 9

In [ ]:
import rdkit.Chem as Chem
from rdkit.Chem import MolFromSmiles, GetAdjacencyMatrix

def get_adjacency_matrix(smiles):
  """
  Get the adjacency matrix for a molecule from its SMILES string.

  Args:
    smiles: The SMILES string of the molecule.

  Returns:
    A numpy array representing the adjacency matrix of the molecule.
  """
  mol = MolFromSmiles(smiles)
  return GetAdjacencyMatrix(mol)

# Example usage
smiles = "Nc1ccncc1"
adjacency_matrix = get_adjacency_matrix(smiles)
print(adjacency_matrix)

[[0 1 0 0 0 0 0]
 [1 0 1 0 0 0 1]
 [0 1 0 1 0 0 0]
 [0 0 1 0 1 0 0]
 [0 0 0 1 0 1 0]
 [0 0 0 0 1 0 1]
 [0 1 0 0 0 1 0]]
